Edge2 no longer with us, Edge back on track

diff --git a/.github/workflows/edge-build.yml b/.github/workflows/edge-build.yml
--- a/.github/workflows/edge-build.yml
+++ b/.github/workflows/edge-build.yml
@@ -15,7 +15,7 @@ on:
 jobs:
   bootstrap:
     name: 🥾 Bootstrap
-    runs-on: ubuntu-22.04
+    runs-on: ubuntu-latest
 
     outputs:
       date: ${{ steps.step1.outputs.date }}
@@ -45,24 +45,41 @@ jobs:
   build-linux:
     name: 🐧 Linux
     needs: bootstrap
-    runs-on: ubuntu-22.04
+    runs-on: ubuntu-latest
+    container: rust:bullseye
     continue-on-error: false
 
     outputs:
       artifact: build-develop-${{ needs.bootstrap.outputs.ref }}-linux
       build_info: Built at ${{ needs.bootstrap.outputs.date }} ${{ needs.bootstrap.outputs.clock }} based on commit ${{ needs.bootstrap.outputs.ref }}.
 
-    steps:
+    steps:   
       - name: 🔗 Checkout source code from github
         uses: actions/checkout@v3
         with:
           token: ${{ secrets.PAT_ALL_REPO }}
           submodules: recursive
+          
+      - name: 🔨 Rust update
+        shell: bash
+        run: |
+          apt update
+          apt install -y mingw-w64
+          
+          rustup install stable
+          rustup default stable
+          rustup target add x86_64-pc-windows-gnu
+          rustup component add rust-std --target x86_64-pc-windows-gnu
+          rustup show
+          rustc --print sysroot
+          
+          which x86_64-w64-mingw32-dlltool || echo "dlltool not found"
+          x86_64-w64-mingw32-dlltool --version
 
       - name: 🛤️ Setup the dotnet build environment
         uses: actions/setup-dotnet@v2
         with:
-          dotnet-version: 9.0.200
+          dotnet-version: 8.0.406
 
       - uses: dtolnay/rust-toolchain@stable
       - uses: ClementTsang/cargo-action@v0.0.3
@@ -70,18 +87,27 @@ jobs:
           command: build
           args: -r --target x86_64-unknown-linux-gnu
           directory: Carbon.Core/Carbon.Native
+          
+      - uses: dtolnay/rust-toolchain@stable
+      - uses: ClementTsang/cargo-action@v0.0.3
+        with:
+          command: build
+          args: -r --target x86_64-pc-windows-gnu
+          directory: Carbon.Core/Carbon.Native
 
       - name: 🔨 Setup the Carbon build environment
         shell: bash
         run: |
-          ${GITHUB_WORKSPACE}/Tools/Build/linux/bootstrap.sh
+          dotnet run --project Carbon.Core/Carbon.Tools/Carbon.Runner Tools/Build/runners/bootstrap.cr
 
       - name: 🐧 Built Carbon on Linux
         shell: bash
         run: |
           export VERSION=${{ needs.bootstrap.outputs.version }}
-          ${GITHUB_WORKSPACE}/Tools/Build/linux/build.sh DebugUnix "EDGE" "edge_build"
-          ${GITHUB_WORKSPACE}/Tools/Build/linux/build.sh MinimalUnix "EDGE" "edge_build"
+          dotnet run --project Carbon.Core/Carbon.Tools/Carbon.Runner Tools/Build/runners/build.cr Debug EDGE edge_build
+          dotnet run --project Carbon.Core/Carbon.Tools/Carbon.Runner Tools/Build/runners/build.cr DebugUnix EDGE edge_build
+          dotnet run --project Carbon.Core/Carbon.Tools/Carbon.Runner Tools/Build/runners/build.cr Minimal EDGE edge_build
+          dotnet run --project Carbon.Core/Carbon.Tools/Carbon.Runner Tools/Build/runners/build.cr MinimalUnix EDGE edge_build
 
       - name: ⬆️ Upload the artifacts
         uses: actions/upload-artifact@v4
@@ -92,50 +118,6 @@ jobs:
             Release/Carbon.Linux.Debug.info
             Release/Carbon.Linux.Minimal.tar.gz
             Release/Carbon.Linux.Minimal.info
-
-  # BUILD WINDOWS --------------------------------------------------------------
-  build-windows:
-    name: 💻 Windows
-    needs: bootstrap
-    runs-on: windows-latest
-    continue-on-error: false
-
-    steps:
-      - name: 🔗 Checkout source code from github
-        uses: actions/checkout@v3
-        with:
-          token: ${{ secrets.PAT_ALL_REPO }}
-          submodules: recursive
-
-      - name: 🛤️ Setup the dotnet build environment
-        uses: actions/setup-dotnet@v2
-        with:
-          dotnet-version: 9.0.200
-
-      - uses: dtolnay/rust-toolchain@stable
-      - uses: ClementTsang/cargo-action@v0.0.3
-        with:
-          command: build
-          args: -r --target x86_64-pc-windows-msvc
-          directory: Carbon.Core/Carbon.Native
-          
-      - name: 🔨 Setup the Carbon build environment
-        shell: cmd
-        run: |
-          %GITHUB_WORKSPACE%\Tools\Build\win\bootstrap.bat
-
-      - name: 🔨 Built Carbon on Windows
-        shell: cmd
-        run: |
-          set VERSION=${{ needs.bootstrap.outputs.version }}
-          call %GITHUB_WORKSPACE%\Tools\Build\win\build.bat Debug EDGE edge_build
-          call %GITHUB_WORKSPACE%\Tools\Build\win\build.bat Minimal EDGE edge_build
-
-      - name: ⬆️ Upload the artifacts
-        uses: actions/upload-artifact@v4
-        with:
-          name: build-develop-windows
-          path: |
             Release/Carbon.Windows.Debug.zip
             Release/Carbon.Windows.Debug.info
             Release/Carbon.Windows.Minimal.zip
@@ -144,8 +126,8 @@ jobs:
   # RELEASE --------------------------------------------------------------------
   release-on-commit:
     name: 💾 Edge Release
-    needs: ["bootstrap", "build-linux", "build-windows"]
-    runs-on: ubuntu-22.04
+    needs: ["bootstrap", "build-linux"]
+    runs-on: ubuntu-latest
 
     steps:
       - name: 🗑️ Delete existing release tag
@@ -195,9 +177,9 @@ jobs:
           files: |
             Release/build-develop-linux/Carbon.Linux.Debug.info
             Release/build-develop-linux/Carbon.Linux.Debug.tar.gz
-            Release/build-develop-windows/Carbon.Windows.Debug.info
-            Release/build-develop-windows/Carbon.Windows.Debug.zip     
+            Release/build-develop-linux/Carbon.Windows.Debug.info
+            Release/build-develop-linux/Carbon.Windows.Debug.zip     
             Release/build-develop-linux/Carbon.Linux.Minimal.info
             Release/build-develop-linux/Carbon.Linux.Minimal.tar.gz
-            Release/build-develop-windows/Carbon.Windows.Minimal.info
-            Release/build-develop-windows/Carbon.Windows.Minimal.zip
+            Release/build-develop-linux/Carbon.Windows.Minimal.info
+            Release/build-develop-linux/Carbon.Windows.Minimal.zip
